### ISSUE TITLE
Would you please clarify and update your settings for License used

### ISSUE THREAD

**Issue by leebrian** [CDCgov/geneflow#13]
Hello there, I'm working on the code.gov inventory for CDC and noticed that [geneflow's license file says Apache 2.0](https://github.com/CDCgov/geneflow/blob/master/LICENSE), but isn't actually Apache 2.0 so the GitHub project profile doesn't know what license it is and is a bit confused. This means GitHub's API returns the license as unknown and our submission is a little less accurate when it comes to geneflow.

Is it possible that you use the apache license unmodified? According to the [GitHub docs](https://help.github.com/en/articles/adding-a-license-to-a-repository) this will then display the license type in an easy and consistent way with other projects and help users and potential users understand your project.

CDC has an example in it's [template repo](https://github.com/CDCgov/template/blob/master/LICENSE) that you can copy.

**Comment by jhphan** [comment]
Sure, it looks like the license file we used is just the bottom section of the Apache license. Not sure how that happened, but I'll fix it today.

**Comment by leebrian** [comment]
Thanks, right. I think y'all are using APL2, but GitHub got confused because it's not a full copy. A minor change, but will help collaborators a little bit. No rush whatsoever as the submission won't take place for a month or so.

**Comment by jhphan** [comment]
Ok, in that case, I'll merge the change to master on Wednesday because we have a planned release that day anyway.

**Comment by jhphan** [comment]
This license file should be updated in master now.
